### ISSUE TITLE
plugin doesn't work with intellij 12 on osx

### ISSUE THREAD

**Issue by astubbs** [Abnaxos/pegdown-doclet#18]
As commented on the plugin page: http://plugins.jetbrains.com/plugin/7253?pr=

> Awesome idea, but doesn't work for me with 12 
> `On startup: failed to initialize and will be disabled`
> `ch/raffael/doclets/pegdown/integrations/idea/TempFileManager : Unsopported`
> `major.minor version 51.0`
> Needs recompiling for 12?

**Comment by jbyler** [comment]
Cross-posting from PR #19:

Looks like we're finally getting close to IntelliJ on Mac OS X with non-Apple Java.  As of 2015-10-01, here is the [support page](https://intellij-support.jetbrains.com/hc/en-us/articles/206827627-IDE-doesn-t-start-after-updating-to-Mac-OS-Yosemite-or-Mavericks) detailing the list of open issues, most of which are fixed now.  Also, the [IDEA 15 preview](http://blog.jetbrains.com/idea/2015/10/intellij-idea-15-preview-is-available/) is available today, and it [uses Java 8](http://blog.jetbrains.com/idea/2015/06/intellij-idea-15-eap-is-open/#osxinstaller).  The JetBrains team apparently gave up on waiting for Oracle to fix the various problems and is shipping with a patched JDK.
