### ISSUE TITLE
Doclet doesn't support generic type arguments (@param <T>)

### ISSUE THREAD

**Issue by pron** [Abnaxos/pegdown-doclet#22]
It says `warning - @param argument "T" is not a parameter name.`

**Comment by daschl** [comment]
For what it's worth I'm seeing the same thing.

```
warning - @param argument "T" is not a parameter name.
```

docblock looks like

```java
     *
     * @param <T> the type returned.
     * @param observable the source {@link Observable}
     * @param timeout the maximum timeout before an exception is thrown.
     * @param tu the timeout unit.
     * @return the extracted value from the {@link Observable} or throws in an error case.
     */
    public static <T> T blockForSingle(final Observable<? extends T> observable, final long timeout,
        final TimeUnit tu) {
```

**Comment by richard-melvin** [comment]
I have same issue: generic arguments to a _type_ are ok, it's a generic argument to an individual _method_ that gets the warning, Not seen the same thing with the standard doclet.

**Comment by slovdahl** [comment]
If you think the fix in my pull request is ok I would really appreciate a new release with the fix included. I would really like to avoid building my own version of the pegdown-doclet library. Thanks in advance!
