### ISSUE TITLE
Check for compatibility with JavaDoc 1.8

### ISSUE THREAD

**Issue by Abnaxos** [Abnaxos/pegdown-doclet#25]
Check if there are any issues when using the doclet with JavaDoc 1.8 and fix them if needed. Also check whether there are any new features that need special support.

Ensure that the doclet remains compatible with JavaDoc 1.7.

**Comment by ddimtirov** [comment]
Javadoc for Java 8 does not use images for backgrounds and the supplied CSS produces a mess.

If we use the original Java8 stylesheet, we lose other customizations - i.e. the syntax highlighting options.
