### ISSUE TITLE
Would you consider changing the license?

### ISSUE THREAD

**Issue by hbf** [Abnaxos/pegdown-doclet#33]
First of all, thanks a lot for this very useful tool; I very much like documenting my code with a modern documentation syntax.

I would like to use the tool but the project I am working on doesn't allow GPL3. I am wondering whether you would be willing to change the license to something else, possibly the Apache license?

From the Github history I see that GPL3 is needed because of _PlantUML_. I quickly checked their website and see that they allow the Apache License, see [here](http://plantuml.sourceforge.net/faq.html). 

In case you could imagine making such a change, I'd be happy to come up with a PR, of course.

**Comment by jfallows** [comment]
+1 :+1:

**Comment by Abnaxos** [comment]
Well, generally, I'm open for that. I don't like the GPL very much myself, I deem the concept of "forced freedom" contradictory.

However, I don't really see why. The Doclet is a compile-level tool. The virus effect of the GPL does *not* extend to the output of GPLed tools. Like it's perfectly OK to compile and publish closed source code using GCC, it's also perfectly OK to generate the docs for a closed source project using pegdown-doclet. The GPL poses no restrictions to the input and/or output of GPLed tools.

So, as long as you're not *deriving* a new or extended tool from pegdown-doclet, the GPL is no issue.

If you're actually deriving something, I'm obviously curious about what it could be. ;)

**Comment by ddimtirov** [comment]
Some organizations have blanket policies, prohibiting using GPL regardless of the use-case (the claim is that this way they eliminate the risk of inappropriate discretion).

**Comment by hbf** [comment]
+1

**Comment by tsjensen** [comment]
:+1:

**Comment by Abnaxos** [comment]
GPL it is.

It's a compile-level tool. As such, the GPL neither affects the license of the input nor the license of the output. That way I'm sure not to clash with PlantUML's GPL (which – BTW – is also a compile-level tool).

Its perfectly legal to use it for documenting commercial or otherwise closed-source code with a proprietary license.
