### ISSUE TITLE
background.gif and other resources missing when running with Java 8

### ISSUE THREAD

**Issue by achohbee** [Abnaxos/pegdown-doclet#34]
When running using the Java 8 version of javadoc, the resources/*.gif files are not included. This is presumably because those files are not used by the new Java 8 default stylesheet.

I've worked around this by having a little script in my pom file download the resource files from the Java 7 API website during the build process, but this isn't really ideal.

**Comment by Abnaxos** [comment]
Done. Maybe, the CSS files still need some fine-tuning, but generally, it should be OK now.
