### ISSUE TITLE
Javadocs task fails when building project

### ISSUE THREAD

**Issue by udeleng** [Abnaxos/pegdown-doclet#35]
I cloned the project locally and ran the "clean build" command. I didn't modify any sources.

> gradle clean build  
      
:clean UP-TO-DATE
:integrations:clean UP-TO-DATE
:integrations:gradle-plugin:clean UP-TO-DATE
:integrations:idea-plugin:clean UP-TO-DATE
:compileJava
:compileGroovy UP-TO-DATE
:processResources
:classes
:jar
:allJar
:javadoc
javadoc: error - Illegal package name: "<a"
javadoc: error - Illegal package name: "href="
javadoc: error - Illegal package name: "https://github.com/Abnaxos/pegdown-doclet/"
javadoc: error - Illegal package name: "target="
javadoc: error - Illegal package name: ">"
javadoc: error - Illegal package name: "<img"
javadoc: error - Illegal package name: "style="
javadoc: error - Illegal package name: "position: absolute; top: 0; right: 0; border: 0;"
javadoc: error - Illegal package name: "src="
javadoc: error - Illegal package name: "https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png"
javadoc: error - Illegal package name: "alt="
javadoc: error - Illegal package name: "Fork me on GitHub"
javadoc: error - Illegal package name: ">"
javadoc: error - Illegal package name: "</a>"
javadoc: error - Illegal package name: ""
javadoc: warning - No source files for package _top
15 errors                
1 warning                
:javadoc FAILED          
              
FAILURE: Build failed with an exception.
              
* What went wrong:
Execution failed for task ':javadoc'.
> Javadoc generation failed.
              
* Try:        
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
              
BUILD FAILED  
              
Total time: 18.459 secs

=================================

I also see errors like this:

15:25:12.848 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainDependencyResolver] Using module 'org.parboiled:parboiled-core:1.1.5' from repository 'BintrayJCenter'
15:25:12.864 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainDependencyResolver] Discarding resolve failure.
java.lang.NullPointerException                                  
        at org.gradle.api.internal.artifacts.repositories.resolver.MavenLocalResolver.isOrphanedPom(MavenLocalResolver.java:49)
        at org.gradle.api.internal.artifacts.repositories.resolver.MavenLocalResolver.findMetaDataArtifact(MavenLocalResolver.java:42)

=====
15:25:12.474 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainDependencyResolver] Using module 'com.google.guava:guava:18.0' from repository 'BintrayJCenter'
15:25:12.474 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainDependencyResolver] Discarding resolve failure.
java.lang.NullPointerException                                  
        at org.gradle.api.internal.artifacts.repositories.resolver.MavenLocalResolver.isOrphanedPom(MavenLocalResolver.java:49)
        at org.gradle.api.internal.artifacts.repositories.resolver.MavenLocalResolver.findMetaDataArtifact(MavenLocalResolver.java:42)

**Comment by Abnaxos** [comment]
Hm. I don't have such issues. Did you use ./gradlew to make sure to be using the right Gradle version? Are you using at least JDK7?

**Comment by udeleng** [comment]
I tried again using **gradlew** and the only errors I got were in regards to signing:

*Cannot perform signing task ':integrations:idea-plugin:signArchives' because it has no configured signatory*

Installing the pegdown-doclet plugin jars from the built project I downloaded resulted in some error in the IDEA (the configuration screen did not display in Intellij). 

Instead, I was able to install pegdown-doclet from the plugins repo (it was the same version). I did enable it for the project and module. I added a "#" in the beginning of one line and pressed CTRL-J (Mac), but the lie was not in bold and the hash symbol displayed as is. I am using IntelliJ 14.

**Comment by fredgirl77** [comment]
I've also experienced both issues listed here: the javadoc task failing, and the "cannot perform signing task" error. I'm using JDK8. If there's any extra info that would help with debugging, let me know.

**Comment by RAnders00** [comment]
The "cannot sign" error is perfectly normal. Developers create signatures of their artifacts with their private keys so you can verify that they are indeed from the original author and not from some untrusted source. Because you are not the original developer, you are not provided the private key that is needed to create the signatures, so this message is normal and expected.

Apart from that, it seems like you are supposed to use `./gradlew` because it uses the gradle version associated with the project and not the latest version (you probably have a newer gradle version which apparently is not compatible with the build settings of this project)

**Comment by Abnaxos** [comment]
I fixed this a long time ago in 1e4b464 :)

The signing task gets disabled if we're not going to upload them to OSSRH.
