### ISSUE TITLE
.jar file

### ISSUE THREAD

**Issue by gherson** [Abnaxos/pegdown-doclet#49]
README.md has under section **Invoking**:
`javadoc -doclet ch.raffael.doclets.pegdown.PegdownDoclet -docletpath /path/to/pegdown-doclet-1.1-all.jar`

When I download pegdown-doclet by clicking the Download ZIP [button](https://github.com/Abnaxos/pegdown-doclet/archive/master.zip), however, I don't see a pegdown-doclet-1.1-all.jar (or other .jar) file.  Why?  Why no other installation instructions?

thank you,
George H

**Comment by Abnaxos** [comment]
The *Download ZIP* button you specified is a link to download the source code from GitHub as ZIP archive, not the binaries. The binaries are located in the Maven repository.

I've updated the README accordingly.
