### ISSUE TITLE
Not working in methods in Android Studio 1.5.1

### ISSUE THREAD

**Issue by lorenzos** [Abnaxos/pegdown-doclet#53]
Strange thing, Pegdown works perfectly for classes and fields docs, but not for methods. No exceptions seems to be thrown. Demonstration:

![byzanz-record](https://cloud.githubusercontent.com/assets/245615/13983927/35ae8cfa-f0f3-11e5-8095-1f0f7bea7fca.gif)

If it looks related to Android Studio to you, I'll file a new issue [here](https://code.google.com/p/android/issues/entry?template=Tools%20bug%20report).

**Comment by Abnaxos** [comment]
I'll have to check the whole `DocumentationProvider` thing for compatibility, there are also other issues reported to that. This also uses classes from `idea.jar`, so it basically uses internal classes that shouldn't be used by plugins, as far as I can understand it.

It's absolutely possible that this is an issue of Android Studio, but I can't really be sure of it. This plugin is a hack …

**Comment by lorenzos** [comment]
I just tried downloading the latest version of IntelliJ (no Android Studio), and the Pegdown plugin, after installing it, works flawlessly also on methods.

Version of Pegdown is 1.2.1 on both.

I'll file the issue for Android Studio as soon as possible if you think it's the best thing to do.

**Comment by aeracode** [comment]
Experienced same issue, but now It works in Android Studio 2.0

**Comment by lorenzos** [comment]
Can confirm it works on Android Studio 2.0. I think this can be closed, 'cause 2.0 came out of beta this month.
